service: file-handler

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-west-1
  environment: ${file(env.yml):${self:provider.stage}}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:ListBucket
      Resource:
        - "Fn::GetAtt": [ Bucket, Arn ]

    - Effect: Allow
      Action:
        - s3:*
      Resource:
        - Fn::Join:
          - ''
          -
            - "Fn::GetAtt": [ Bucket, Arn ]
            - "/*"

functions:
  hello:
    handler: file_transfer/handler.s3_file_handler
    events:
      - s3:
          bucket: ${self:provider.environment.BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - prefix: Incoming/
          existing: true

resources:
  Resources:
    Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.BUCKET_NAME}
  Outputs:
    BucketName:
      Value:
        Ref: Bucket
